### ISSUE TITLE
DividerItemDecoration is not drawn

### ISSUE THREAD

**Issue by Cybrosys** [jamesmontemagno/FloatingActionButton-for-Xamarin.Android#10]
DrawVertical
var left = parent.PaddingLeft;
var right = parent.PaddingRight;

The above causes a divider.SetBounds to be 0px in width. The correct solution would be:
var left = parent.PaddingLeft; // Maybe even parent.Left + parent.PaddingLeft?
var right = parent.Right - parent.PaddingRight;

The same problem exists in DrawHorizontal with the bounds set being 0px in height;

**Comment by jamesmontemagno** [comment]
This library is no longer updated or supported as the official version is in the Support Design Library. You can submit a pull request if you would like.
