### ISSUE TITLE
Adding more than one FAB to recycleview

### ISSUE THREAD

**Issue by mstryb** [jamesmontemagno/FloatingActionButton-for-Xamarin.Android#11]
I noticed that i cannod attach more than one fab to one recycleview.
I have 3 buttons placed in row aligned right bottom of the viewport and only the one that is attached last will move while view is scrolled. The rest of them stays in place.
Is that something that may be implemented? or should i find some custom solution for that?

**Comment by jamesmontemagno** [comment]
This library is no longer updated or supported as the official version is in the Support Design Library
