### ISSUE TITLE
How to attach to a ScrollView?

### ISSUE THREAD

**Issue by zipgenius** [jamesmontemagno/FloatingActionButton-for-Xamarin.Android#13]
Hello.
I tried to attach the FAB to a ScrollView but it seems I have to use "com.refractored.fab.ObservableScrollView", which appears as a gray rectangle in the UI designer.
How can I attach the FAB to a ScrollView already available in my XML?

**Comment by jamesmontemagno** [comment]
You must use the ObservableScrollView as it has events to tie into.
