### ISSUE TITLE
no command for XAML binding

### ISSUE THREAD

**Issue by Sokti** [jamesmontemagno/FloatingActionButton-for-Xamarin.Android#16]
Hi, 
i'm using this in Forms XAML (targeting Android platform) and it seems not be possible to bind to a Command without Codebehind. TapGestureRecognizer is not triggered and EventToCommandBehavior will not work on the available Click-Action. Any other way to bind to an Command of my ViewModel?

Cheers,
Benny

**Comment by jamesmontemagno** [comment]
There is There is a Clicked  event that you can bind to.

**Comment by jamesmontemagno** [comment]
Adding as feature request.
