### ISSUE TITLE
 Adding this control to a Xamarin forms project

### ISSUE THREAD

**Issue by jd-alexander** [jamesmontemagno/FloatingActionButton-for-Xamarin.Android#2]
Great library. How would I go about adding it  to  a Xamarin Forms project?  I understand the whole concept of  custom renderers, but I can't seem to understand how the button will be attached to the underlying list view.

**Comment by jamesmontemagno** [comment]
This is not possible as Forms does not currently support AppCompat, but you can always create your own custom control for Xamarin.Forms. I have no plans to do this though.
