### ISSUE TITLE
Getting exception while trying to implement on Xamarin.Forms project

### ISSUE THREAD

**Issue by ShahriatHossain** [jamesmontemagno/FloatingActionButton-for-Xamarin.Android#20]
Getting such error:
Error	CS0400	The type or namespace name 'Refractored' could not be found in the global namespace (are you missing an assembly reference?)

Here I have tried to implement your instruction:

Integration Xamarin.Forms

See sample app for integration

XAML Example:

<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="Microsoft.Mvpui.ContributionsPage"
             xmlns:fab="clr-namespace:Refractored.FabControl;assembly=Refractored.FabControl">

    <ContentPage.Content>
		<AbsoluteLayout VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand">
				<ListView 
						  AbsoluteLayout.LayoutFlags="All"
						  AbsoluteLayout.LayoutBounds="0,0,1,1">

			</ListView>
			<fab:FloatingActionButtonView
				ImageName="toolbar_add.png"
				ColorNormal="{StaticResource Primary}"
				ColorPressed="{StaticResource PrimaryDark}"
				ColorRipple="{StaticResource PrimaryDark}"
				x:Name="FloatingActionButtonAdd"
				IsVisible="False"
				AbsoluteLayout.LayoutFlags="PositionProportional"
				AbsoluteLayout.LayoutBounds="1, 1, AutoSize, AutoSize"/>
		</AbsoluteLayout>
	</ContentPage.Content>
</ContentPage>

**Comment by jamesmontemagno** [comment]
Did you add the fab namespace? I do it here: https://github.com/Microsoft/mvp/blob/master/MVP/MVPUI/ContributionsPage.xaml

**Comment by achargoy** [comment]
Hi James
I add the fab namespace but I get the same error like ShahriatHossain

**Comment by jamesmontemagno** [comment]
Works great for me you can look at the sample. Make sure you install it into all of your projects.
