### ISSUE TITLE
Adding the assembly messes with the colors in my app

### ISSUE THREAD

**Issue by obartelt** [jamesmontemagno/FloatingActionButton-for-Xamarin.Android#21]
Just by adding the NuGet package/the assembly, the colors for my overflow button, the lines in the navigation drawer, etc. get messed up. Any idea on how that's even possible? Or is it due to the problems in the 15.4 Xamarin (Android) release?

**Comment by jamesmontemagno** [comment]
no clue, works fine for me. make sure all support libraries are updated and the same.
