### ISSUE TITLE
Could not install package 'Refractored.FloatingActionButton 2.1.0'.

### ISSUE THREAD

**Issue by kyleward** [jamesmontemagno/FloatingActionButton-for-Xamarin.Android#22]
Hi,

Thanks for this plugin. I'm getting the following error when installing the package:

Could not install package 'Refractored.FloatingActionButton 2.1.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111'

Any ideas or work arounds?

**Comment by jamesmontemagno** [comment]
Correct... needs to be installed in an Android project...
