### ISSUE TITLE
Does not support .netstandard2.0 PCL

### ISSUE THREAD

**Issue by NicholasBusby** [jamesmontemagno/FloatingActionButton-for-Xamarin.Android#23]
Can't install this into a .netstandard2.0 Forms PCL
> Severity	Code	Description	Project	File	Line	Suppression State
Error		Package Refractored.FloatingActionButton 2.1.0 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package Refractored.FloatingActionButton 2.1.0 supports: monoandroid10 (MonoAndroid,Version=v1.0)			0

**Comment by jamesmontemagno** [comment]
yes, it is only for Android. Unless you install the forms version of it.
