### ISSUE TITLE
Support or Alternative for Xamarin AndroidX

### ISSUE THREAD

**Issue by roninstar** [jamesmontemagno/FloatingActionButton-for-Xamarin.Android#25]
Hi James, we are upgrading our Xamarin Android project to use Xamarin AndroidX support libraries.  We would like to keep using your FloatingActionButton but it has dependencies on the old Xamarin Support libraries that are deprecated.  Do you have any alternative Floating ActionButton recommendations we can use or could you upgrade this package to support AndroidX. This is the error we have:
Refractored.FloatingActionButton 2.1.0 -> Xamarin.Android.Support.v7.RecyclerView 25.4.0.2 -> Xamarin.Android.Support.Compat (= 25.4.0.2)
Thanks so much James for any help you can offer!
Mark

**Comment by jamesmontemagno** [comment]
Try 3.0.0-beta

**Comment by roninstar** [comment]
Great thanks so much James. You are the best!
Mark
