### ISSUE TITLE
Empty Nuget after update to AndroidX

### ISSUE THREAD

**Issue by JakubFojtik** [jamesmontemagno/FloatingActionButton-for-Xamarin.Android#26]
Hi, thank you for updating the dependencies!
Sadly the preview Nuget does not contain the FAB library itself (11KB vs previous 80KB), would you consider updating it?

When compiled from source the FAB seems to work well, did you encounter any problems so far with AndroidX? Or do you think the library is ready for use?

**Comment by jamesmontemagno** [comment]
Will look at it... probably a packaging issue.

**Comment by jamesmontemagno** [comment]
try 3.0.1-beta

**Comment by JakubFojtik** [comment]
Works, thanks.
