### ISSUE TITLE
Android.Support.V7.Widget.SearchView crash when installing this component

### ISSUE THREAD

**Issue by xleon** [jamesmontemagno/FloatingActionButton-for-Xamarin.Android#3]
If I just install either the component or the nugget package (without implementing the code) I get a conflict with support SearchView (android.support.v7.widget.SearchView).
I´m using the SearchView on a menu inflated in an appCompat toolbar:

```
<menu xmlns:android="http://schemas.android.com/apk/res/android" 
      xmlns:local="http://schemas.android.com/apk/res-auto">

    <item 
        android:id="@+id/stockActionSearch"
        android:title="Buscar productos"
        android:icon="@drawable/ic_magnify"
        local:showAsAction="ifRoom|collapseActionView"
        local:actionViewClass="android.support.v7.widget.SearchView" />
```

If I remove the package (FloatingActionButton) everything works as it was before.
And this is the error I´m getting:

[AbsListView] checkAbsListViewlLogProperty get invalid command
[SurfaceTextureClient] [void android::SurfaceTextureClient::init()] debug.stc.fps: 3000 ms
[SupportMenuInflater] Cannot instantiate class: android.support.v7.widget.SearchView
[SupportMenuInflater] java.lang.reflect.InvocationTargetException
[SupportMenuInflater]   at java.lang.reflect.Constructor.constructNative(Native Method)
[SupportMenuInflater]   at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
[SupportMenuInflater]   at android.support.v7.internal.view.SupportMenuInflater$MenuState.newInstance(SupportMenuInflater.java:499)
[SupportMenuInflater]   at android.support.v7.internal.view.SupportMenuInflater$MenuState.setItem(SupportMenuInflater.java:458)
[SupportMenuInflater]   at android.support.v7.internal.view.SupportMenuInflater$MenuState.addItem(SupportMenuInflater.java:479)
[SupportMenuInflater]   at android.support.v7.internal.view.SupportMenuInflater.parseMenu(SupportMenuInflater.java:196)
[SupportMenuInflater]   at android.support.v7.internal.view.SupportMenuInflater.inflate(SupportMenuInflater.java:118)
[SupportMenuInflater]   at md51c1f71399a3dc7cceeb82c8a1c1b18b5.StockView.n_onCreateOptionsMenu(Native Method)
[SupportMenuInflater]   at md51c1f71399a3dc7cceeb82c8a1c1b18b5.StockView.onCreateOptionsMenu(StockView.java:38)
[SupportMenuInflater]   at android.support.v4.app.Fragment.performCreateOptionsMenu(Fragment.java:1868)
[SupportMenuInflater]   at android.support.v4.app.FragmentManagerImpl.dispatchCreateOptionsMenu(FragmentManager.java:1999)
[SupportMenuInflater]   at android.support.v4.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:276)
[SupportMenuInflater]   at android.support.v7.app.ActionBarActivity.superOnCreatePanelMenu(ActionBarActivity.java:273)
[SupportMenuInflater]   at android.support.v7.app.ActionBarActivityDelegate$1.onCreatePanelMenu(ActionBarActivityDelegate.java:80)
[SupportMenuInflater]   at android.support.v7.widget.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:49)
[SupportMenuInflater]   at android.support.v7.internal.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:457)
[SupportMenuInflater]   at android.support.v7.internal.app.ToolbarActionBar$1.run(ToolbarActionBar.java:68)
[SupportMenuInflater]   at android.os.Handler.handleCallback(Handler.java:615)
[SupportMenuInflater]   at android.os.Handler.dispatchMessage(Handler.java:92)
[SupportMenuInflater]   at android.os.Looper.loop(Looper.java:153)
[SupportMenuInflater]   at android.app.ActivityThread.main(ActivityThread.java:5086)
[SupportMenuInflater]   at java.lang.reflect.Method.invokeNative(Native Method)
[SupportMenuInflater]   at java.lang.reflect.Method.invoke(Method.java:511)
[SupportMenuInflater]   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:821)
[SupportMenuInflater]   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
[SupportMenuInflater]   at dalvik.system.NativeStart.main(Native Method)
[SupportMenuInflater] Caused by: java.lang.ClassCastException: android.widget.LinearLayout cannot be cast to android.support.v7.widget.SearchView$SearchAutoComplete
[SupportMenuInflater]   at android.support.v7.widget.SearchView.<init>(SearchView.java:284)
[SupportMenuInflater]   at android.support.v7.widget.SearchView.<init>(SearchView.java:269)
[SupportMenuInflater]   at android.support.v7.widget.SearchView.<init>(SearchView.java:265)
[SupportMenuInflater]   ... 26 more
[Mono] DllImport attempting to load: '/system/lib/liblog.so'.
[Mono] DllImport loaded library '/system/lib/liblog.so'.
[Mono] DllImport searching in: '/system/lib/liblog.so' ('/system/lib/liblog.so').
[Mono] Searching for '__android_log_print'.
[Mono] Probing '__android_log_print'.
[Mono] Found as '__android_log_print'.
[MonoDroid] UNHANDLED EXCEPTION:
[MonoDroid] System.NullReferenceException: Object reference not set to an instance of an object
[MonoDroid] at Chef360.Droid.Views.StockView.OnCreateOptionsMenu (Android.Views.IMenu,Android.Views.MenuInflater) [0x00041] in /Users/xleon/Projects/Chef360/Chef360.Mobile/Chef360.Droid/Views/Fragments/StockView.cs:54
[MonoDroid] at Android.Support.V4.App.Fragment.n_OnCreateOptionsMenu_Landroid_view_Menu_Landroid_view_MenuInflater_ (intptr,intptr,intptr,intptr) <IL 0x0001c, 0x00147>
[MonoDroid] at (wrapper dynamic-method) object.cbd0d72b-f793-49e0-ad87-ff0b2d3f46f7 (intptr,intptr,intptr,intptr) <IL 0x0001d, 0x0005b>

**Comment by jamesmontemagno** [comment]
I have been able to use both of thees together just fine in my sample app. Are you sure that all of your NuGet packages for support are the latest version v22?

Additionally, in your project settings can you make sure that your Compile with is set to API 21.

You will also want to clean your solution and re-build if you are updating your support packages.

**Comment by xleon** [comment]
After hardcore clean (deleting bin and obj folders) it works perfectly!
